version: '3'
services:
  app:
    build: .
    env_file:
      - ./environments/db.env
    command: bash -c "rm -f tmp/pids/server.pid && \
             bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./environments/db.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: ./nginx
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "80:80"
    depends_on:
      - app
